### ISSUE TITLE
Add support for `x [day|week|month|year]s ago` and `x [day|week|month|year]s from now`

### ISSUE THREAD

**Issue by marutypes** [ForbesLindesay/dehumanize-date#1]
## Add support for `x [day|week|month|year]s ago` and `x [day|week|month|year]s from now`

This should be a relatively simple addition, and adds a lot of functionality for natural language style date strings. The use case I want this for is in a cli-tool. I'll look into adding this myself later this weekend :).

**Comment by ForbesLindesay** [comment]
That would be great :+1:

**Comment by JeromeFitz** [comment]
Pending approval, there will be initial support for `[day|week]s`

Could probably stand to have some code cleanup in anticipation for adding `[month|year]s`

Would the expected behavior be:

**now = 2000-01-05**
1 month from now: 2000-02-05
2 months from now: 2000-03-05
1 year from now: 2001-01-05
2 years from now: 2002-01-05

**now = 2000-01-31**
1 month from now: 2000-02-29
2 months from now: 2000-03-31
3 months from now: 2000-04-30
1 month ago: 1999-12-31
2 months ago: 1999-11-30
3 months ago: 1999-10-31

As in for `[month]s` we take the month and find the same _day_ within, or its max equivalent?

**now: 2000-02-29**
1 year from now: 2001-02-28

**Comment by ForbesLindesay** [comment]
#12 seems to have resolved this.
